version: '3.9'
services:
  odoo:
    image: ${ODOO_IMAGE}
    container_name: odoo${ODOO_VER}
    restart: always
    depends_on:
      - db
    command: ${ODOO_COMMAND:-odoo}
    ports:
      - ${ODOO_WEB_PORT:-8069}:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ${ODOO_CONFIG:-./instances/default/config}:/etc/odoo
      - ${ODOO_ADDONS:-./instances/default/addons}:/mnt/extra-addons
      - ${ODOO_LOG:-./instances/default/log}:/var/log/odoo

  db:
    image: ${POSTGRES_IMAGE}
    container_name: db_odoo${ODOO_VER}
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - FETCH_OCA_DEPENDENCIES=True
      - METABASE_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: ${PGADMIN_IMAGE}
    container_name: pga${ODOO_VER}
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - ${PGADMIN_WEB_PORT}:80
    profiles: 
      - pgadmin
    depends_on:
      - odoo
      - db

  metabase:
    image: ${MB_IMAGE}
    container_name: metabase${ODOO_VER}
    restart: unless-stopped
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_DB_NAME:-metabase}
      MB_DB_PORT: ${MB_DB_PORT:-5432}
      MB_DB_USER: $POSTGRES_USER
      MB_DB_HOST: db_odoo$ODOO_VER
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_ENCRYPTION_SECRET_KEY: '$MB_ENCRYPTION_SECRET_KEY'
      JAVA_TIMEZONE: '$MB_JAVA_TIMEZONE'
    ports:
      - '${MB_WEB_PORT}:3000'
    profiles: 
      - metabase
    depends_on:
      - odoo
      - db

volumes:
  odoo-web-data:
  pgadmin-data:
  odoo-db-data:
